In [1]:
import torch
from torch.nn.utils.rnn import pad_sequence

def collate_fn(data):
    """
    Hàm số này sẽ được sử dụng để pad session về max length
    Args:
      data: batch truyền vào
    return:
      batch data đã được pad length có shape maxlen x batch_size
    """
    # Sort batch theo độ dài của input_sequence từ cao xuống thấp
    data.sort(key=lambda x: len(x[0]), reverse=True)
    lens = [len(sess) for sess, label in data]
    labels = []
    # Padding batch size
    # padded_sesss = torch.zeros(len(data), max(lens)).long()
    # for i, (sess, label) in enumerate(data):
    #     padded_sesss[i,:lens[i]] = torch.LongTensor(sess)
    #     labels.append(label)

    # print(padded_sesss)
    inputs = []
    for s, l in data:
      inputs.append(torch.LongTensor(s))
      labels.append(l)
    padded_sesss = pad_sequence(inputs)


    # Transpose dữ liệu từ batch_size x maxlen --> maxlen x batch_size
    # padded_sesss = padded_sesss.transpose(0,1)
    return padded_sesss, torch.tensor(labels).long(), lens

In [31]:
data =  [ [[1, 2, 3], [1]], [[1], [3]] ]

feature_data={
    1: [44, 55, 66],
    2: [34, 445, 665],
    3: [1278, 93, 30]
}

# print(data)
# data.sort(key=lambda x: len(x[0]), reverse=False)

# print(data)
print("---------")
x = collate_fn(data)
input_seq = x[0]
print("input_seq:",input_seq)
print(input_seq.shape)
# print(input_seq.view(-1, 1))

x1 = input_seq.view(-1, 1).expand(-1, 3).clone()
# print("x1:", x1)
# print("x1:", x1.shape)

print("for loopp -------")
for i, xx1 in enumerate(input_seq.flatten()):
    if xx1 == 0:
        continue
    x1[i] = torch.tensor(feature_data[xx1.item()])

#   print(xx1)
#   print(torch.tensor(feature_data[xx1.item()]))
  
  # x1[i] = torch.tensor(feature_data[xx1.item()])

print("x1 after:", x1)

print("---------")
x1 = x1.view(3,2, 3)
print("x1 after:", x1)
print(x1.shape)

# print("---------")
# print(x1.view(input_seq.shape))

# x = torch.zeros(3, 2).long()
# print(x)
# for i1 in input_seq:
#   for i2 in i1:



---------
input_seq: tensor([[1, 1],
        [2, 0],
        [3, 0]])
torch.Size([3, 2])
for loopp -------
x1 after: tensor([[  44,   55,   66],
        [  44,   55,   66],
        [  34,  445,  665],
        [   0,    0,    0],
        [1278,   93,   30],
        [   0,    0,    0]])
---------
x1 after: tensor([[[  44,   55,   66],
         [  44,   55,   66]],

        [[  34,  445,  665],
         [   0,    0,    0]],

        [[1278,   93,   30],
         [   0,    0,    0]]])
torch.Size([3, 2, 3])


In [35]:
x = torch.tensor([[1, 1],
        [2, 0],
        [3, 0]])
print(x.shape)
print(x)
print(x.permute(1, 0))

torch.Size([3, 2])
tensor([[1, 1],
        [2, 0],
        [3, 0]])
tensor([[1, 2, 3],
        [1, 0, 0]])


In [6]:
import numpy as np

In [20]:
def categorical_cross_entropy(t_list,p_list):
    t_list = np.float_(t_list)
    p_list = np.float_(p_list)
    losses = []
    for t,p in zip(t_list,p_list):
      loss = -np.sum(t * np.log(p))
      losses.append(loss)
      print(f't:{t}, p:{p},loss:{loss}\n')
    return np.sum(losses)

In [23]:
t_list = [[0,1,0, 0, 0, 0, 0, 0, 0]]
p_list = [[0.29,0.000001,0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]]
categorical_cross_entropy(t_list,p_list)

13.815510557964274
t:[0. 1. 0. 0. 0. 0. 0. 0. 0.], p:[2.9e-01 1.0e-06 1.0e-01 1.0e-01 1.0e-01 1.0e-01 1.0e-01 1.0e-01 1.0e-01],loss:13.815510557964274



13.815510557964274

In [24]:
np.log(p_list)

array([[ -1.23787436, -13.81551056,  -2.30258509,  -2.30258509,
         -2.30258509,  -2.30258509,  -2.30258509,  -2.30258509,
         -2.30258509]])